name: Feature Request
description: Propose an enhancement or new feature
labels: ["enhancement"]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions or workarounds you've considered...
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What should be included and what should be out of scope?
      value: |
        **In Scope:**
        - 
        
        **Out of Scope:**
        - 
      render: markdown
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Potential Risks or Challenges
      description: Are there any risks, challenges, or concerns with this feature?
      placeholder: Performance concerns, breaking changes, compatibility issues...
    validations:
      required: false

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Algorithm/Model
        - New Project/Example
        - Documentation Enhancement
        - Performance Improvement
        - Visualization Enhancement
        - Data Processing Tool
        - Developer Tool/Utility
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (Critical for my use case)
        - Medium (Would be very helpful)
        - Low (Nice to have)
    validations:
      required: false

  - type: textarea
    id: educational_value
    attributes:
      label: Educational Value
      description: How does this feature enhance the learning experience?
      placeholder: This would help learners understand...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Provide examples from other projects, papers, or resources.
      placeholder: Links to similar implementations, research papers, tutorials...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request.
      placeholder: Any additional information that might help...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: I am willing to help implement this feature (optional)
          required: false
